In [1]:
import tensorflow as tf

Creating Tensors



In [2]:
string = tf.Variable('WhyDoThis',tf.string)
number = tf.Variable(9243, tf.int16)
floating  = tf.Variable(4.655, tf.float64) 

Rank of Tensors

In [3]:
tensor_with_rank1 = tf.Variable([[12],[11]],tf.int32)
tensor_with_rank2 = tf.Variable([[[[1,2,9],[1,5,32]],[[13,4,5],[1,3,2]]],[[[1,2,9],[1,5,32]],[[13,4,5],[1,3,2]]]],int)

In [4]:
tf.rank(tensor_with_rank1)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [5]:
tf.rank(tensor_with_rank2)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

Shape of Tensors

In [6]:
tensor_with_rank2.shape

TensorShape([2, 2, 2, 3])

Change Shape of a Tensor

In [7]:
allones1 = tf.ones([1,2,3])
allones2 = tf.reshape(allones1,[3,2,1])
print(allones1)
print(allones2)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]]

 [[1.]
  [1.]]

 [[1.]
  [1.]]], shape=(3, 2, 1), dtype=float32)


TF Sessions

#### Below code is used when we want the value from a tensor having an object. Note I have not created an object in tensor so it wont run

In [ ]:
with tf.compat.v1.Session() as sess:
   tensorname.eval()